# Generated by Django 3.2.5 on 2021-07-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='createBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField()),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=20)),
            ],
        ),
    ]
