# Generated by Django 3.2.5 on 2021-07-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_createblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='createblog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
