# Generated by Django 3.2.5 on 2021-07-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_createblog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='createblog',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
