# Generated by Django 3.2.5 on 2021-07-27 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
    ]
