# Generated by Django 3.2.5 on 2021-07-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_delete_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
