# Generated by Django 3.2.5 on 2022-01-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_contact_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='createblog',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
